---
output: pdf_document
geometry: margin=1.5cm
header-includes:
  - \usepackage{booktabs}
  - \usepackage{tabu}
  - \usepackage{longtable}
  - \usepackage{caption}
---

\captionsetup[figure]{labelformat=empty}

```{r setup-supp-fig, include = FALSE}
# knitr.table.format = "latex" not necessary
knitr::opts_chunk$set(
  cache.extra = knitr::rand_seed, 
  message = FALSE, 
  warning = FALSE, 
  error = FALSE, 
  echo = FALSE, 
  fig.pos = "H")
# disable sci number format
options(scipen = 999)
# tools
library(here)
library(pander)
library(papaja)
library(captioner)
# data wrangling
library(tidyverse)
# statistical modeling
library(emmeans)
library(multcompView)
library(lsr)
library(pROC)
# result plots
library(ggpubr)
library(ggcorrplot)
library(Hmisc)
library(plotROC)
# images
library(png)
library(grid)
library(gridExtra)
library(gtable)
# constant variables
emotion_list <- c(
  "anger", 
  "disgust", 
  "fear", 
  "happiness", 
  "sadness", 
  "surprise"
  )
name_convention <- c(
  "Human\nObservers",
  "Affectiva",
  "CrowdEmotion",
  "Emotient",
  "Microsoft",
  "MorphCast",
  "Neurodatalab",
  "VicarVision",
  "VisageTech."
  )
classifier_automatic <- c(
  "Affectiva",
  "CrowdEmotion",
  "Emotient", 
  "Microsoft",
  "MorphCast",
  "Neurodatalab",
  "VicarVision",
  "VisageTechnologies"
  )
classifier_level <- c(
  "Humans",
  "Affectiva",
  "CrowdEmotion",
  "Emotient", 
  "Microsoft",
  "MorphCast",
  "Neurodatalab",
  "VicarVision",
  "VisageTechnologies"
  )
```

```{r captions-supp-fig, include=FALSE}
caption_1 <- "S1 Figure. Emotion confusion matrices for human observers and automatic classifiers separately by posed and spontaneous expressions. For cases with ‘undetermined’ confidence levels, the sum of the marginal proportion of recognized emotions can be higher than 100\\%."

caption_2 <- "S2 Figure. Mean values and standard deviations of the Area Under the Curve (AUC) by type of expression for every combination of the 14 human observers."
```

```{r data-supp-fig}
# humans -----------------------------------------------------------------------
humans_data <- here::here("data/humans_data.RDS") %>% 
  readr::read_rds() 

humans_scores <- here::here("data/humans_scores.rds") %>% 
  readr::read_rds()
# machines ---------------------------------------------------------------------
machines_data <- here::here("data/machines_data.rds") %>% 
  readr::read_rds()

machines_scores <- here::here("data/machines_scores.rds") %>% 
  readr::read_rds()
# all --------------------------------------------------------------------------
all_data <- here::here("data/all_data.rds") %>% 
  readr::read_rds()
```

```{r confusion-matrix, fig.cap=caption_1, fig.height=9}
confusion_grid <- expand.grid(
  system = classifier_automatic,
  database = 
    c("Spontaneous\nExpressions","Posed\nExpressions"),
  video_emotion = emotion_list,
  label_emotion = 
    c("undetermined", emotion_list)) %>%
  dplyr::mutate_if(is.factor,as.character)

machines_scores %>%
  dplyr::ungroup() %>%
  dplyr::select(system, database, video_emotion, label_emotion, matching_score) %>%
  dplyr::full_join(
    confusion_grid, 
    by = c("system","database","video_emotion","label_emotion")
    ) %>% 
  dplyr::full_join(
    humans_scores,
    by = c("system","database","video_emotion","label_emotion","matching_score")
    ) %>%
  replace(is.na(.), 0) %>%
  dplyr::mutate(system = factor(system, levels = classifier_level, labels = name_convention)) %>%
  dplyr::mutate(label_emotion = factor(
    label_emotion,
    levels = c("undetermined", "other", emotion_list)
    ))  %>% 
  ggplot(aes(x = video_emotion,y = label_emotion,fill = matching_score)) +
  geom_tile() +
  geom_text(aes(label = scales::percent(matching_score)),
            color = "black",
            size = 2,
            family="serif",
            parse = FALSE, 
            lineheight = 0.7
  ) +
  facet_grid(system~database, scales = "free_y") +
  scale_fill_gradient(
    name = "Recognition Frequency",
    low = "white", 
    high = "red", 
    limits=c(0, 1), 
    labels = scales::percent) +
  scale_x_discrete(name = "Emotion Displayed") +
  scale_y_discrete(name = "Emotion Recognized") +
  theme_minimal() +
  theme(
    text = element_text(size = 10, family = "serif"),
    axis.text.x = element_text(angle = 45, hjust = 0.75, vjust = 0.9),
    strip.text.x = element_text(face = "bold", size = 12),
    strip.text.y = element_text(size = 9),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
    legend.text = element_text(size = 8),
    legend.position = "bottom"
    )
```
